webtalk_init -webtalk_dir E:/Grade4th/XilinxSchool/Project/Colorful-LED/Colorful-LED/Colorful-LED.sim/sim_1/behav/xsim/xsim.dir/RGB_LED_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Jul 27 15:08:07 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "b2b02090-bd3b-4e34-9b87-507550e5b105" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2dfb21cb99214591b84f9be187395620" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2808 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1001 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.56_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "12904_KB" -context "xsim\\usage"
webtalk_transmit -clientid 826151966 -regid "" -xml E:/Grade4th/XilinxSchool/Project/Colorful-LED/Colorful-LED/Colorful-LED.sim/sim_1/behav/xsim/xsim.dir/RGB_LED_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/Grade4th/XilinxSchool/Project/Colorful-LED/Colorful-LED/Colorful-LED.sim/sim_1/behav/xsim/xsim.dir/RGB_LED_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/Grade4th/XilinxSchool/Project/Colorful-LED/Colorful-LED/Colorful-LED.sim/sim_1/behav/xsim/xsim.dir/RGB_LED_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
