# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/system.xdc

# IP: ip/Driver_SK6805_0_1/Driver_SK6805_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Driver_SK6805_0 || ORIG_REF_NAME==Driver_SK6805_0} -quiet] -quiet
