# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Grade4th/XilinxSchool/Project/XilinxSummerSchool/Camera_Demo/Camera_Demo/Camera_Demo.srcs/sources_1/ip/RGB_LED_0_1/RGB_LED_0.xci
# IP: The module: 'RGB_LED_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/Grade4th/XilinxSchool/Project/XilinxSummerSchool/Grade4th/XilinxSchool/Project/Colorful-LED/Colorful-LED/Colorful-LED.srcs/sources_1/ip/Clk_Division_0/Clk_Division_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Clk_Division_0 || ORIG_REF_NAME==Clk_Division_0} -quiet] -quiet

# IP: e:/Grade4th/XilinxSchool/Project/XilinxSummerSchool/Grade4th/XilinxSchool/Project/Colorful-LED/Colorful-LED/Colorful-LED.srcs/sources_1/ip/Driver_SK6805_0_1/Driver_SK6805_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Driver_SK6805_0 || ORIG_REF_NAME==Driver_SK6805_0} -quiet] -quiet

# XDC: e:/Grade4th/XilinxSchool/Project/XilinxSummerSchool/Grade4th/XilinxSchool/Project/Colorful-LED/Colorful-LED/Colorful-LED.srcs/constrs_1/new/system.xdc
# XDC: The top module name and the constraint reference have the same name: 'RGB_LED_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/Grade4th/XilinxSchool/Project/XilinxSummerSchool/Camera_Demo/Camera_Demo/Camera_Demo.srcs/sources_1/ip/RGB_LED_0_1/RGB_LED_0.xci
# IP: The module: 'RGB_LED_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/Grade4th/XilinxSchool/Project/XilinxSummerSchool/Grade4th/XilinxSchool/Project/Colorful-LED/Colorful-LED/Colorful-LED.srcs/sources_1/ip/Clk_Division_0/Clk_Division_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Clk_Division_0 || ORIG_REF_NAME==Clk_Division_0} -quiet] -quiet

# IP: e:/Grade4th/XilinxSchool/Project/XilinxSummerSchool/Grade4th/XilinxSchool/Project/Colorful-LED/Colorful-LED/Colorful-LED.srcs/sources_1/ip/Driver_SK6805_0_1/Driver_SK6805_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Driver_SK6805_0 || ORIG_REF_NAME==Driver_SK6805_0} -quiet] -quiet

# XDC: e:/Grade4th/XilinxSchool/Project/XilinxSummerSchool/Grade4th/XilinxSchool/Project/Colorful-LED/Colorful-LED/Colorful-LED.srcs/constrs_1/new/system.xdc
# XDC: The top module name and the constraint reference have the same name: 'RGB_LED_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
